spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: ***
  jpa:
    hibernate:
      ddl-auto: validate
  jackson:
    serialization:
      write_dates_as_timestamps: true
security:
  oauth2:
    client:
      client-id: client_id
      client-secret: secret
      authorized-grant-types: client_credentials, refresh_token
      scope: read, write
flyway:
  locations: db/migration/