CREATE TABLE "user" (
  ID SERIAL PRIMARY KEY,
  EMAIL VARCHAR(50) UNIQUE NOT NULL,
  PASSWORD VARCHAR(255) NOT NULL,
  FULLNAME VARCHAR(100),
  IS_ENABLED BOOLEAN,
  AVATAR BYTEA,
  BIRTHDAY TIMESTAMP
)